# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d118648c4d8623dc9b0782843ab3e272870a4b8098ec3f28284b5bff5b9d7083710ad5e03c2fae58ad207c1b7b5291375874ff25733d3ff340871a2c77edc1f

test:
  secret_key_base: 30058e5d6ce8d5c042e3684504e4ae44bde06d058b8389921dd8111466cc4337ebdf92c498b990849531437f9e9183109e49a2a9baee0fa95b3a0be2ec74b046

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
